#!/usr/bin/env python3
"""Generate docs/CURATED_REGISTRY.md from agentshare.dev verified registry API.

Source of truth: https://agentshare.dev/api/v1/registry/entries
This file is a thin GitHub mirror for discoverability — not the AgentShare product MCP catalog.
"""
from __future__ import annotations

import json
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

API_URL = "https://agentshare.dev/api/v1/registry/entries?limit=200&sort=new"
REGISTRY_HTML = "https://agentshare.dev/registry"
USER_AGENT = "AgentShare-CuratedRegistrySync/1.0 (+https://github.com/anhmtk/agentshare-mcp)"
OUT_REL = Path("docs/CURATED_REGISTRY.md")


def _esc_cell(value: object) -> str:
    s = "" if value is None else str(value)
    return s.replace("|", "\\|").replace("\n", " ").strip()


def _md_link(label: str, url: str | None) -> str:
    if not url:
        return "—"
    return f"[{_esc_cell(label)}]({url})"


def fetch_entries() -> tuple[list[dict], dict]:
    req = urllib.request.Request(
        API_URL,
        headers={
            "User-Agent": USER_AGENT,
            "Accept": "application/json",
        },
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=45) as resp:
        raw = json.loads(resp.read().decode("utf-8"))
    if not isinstance(raw, dict) or raw.get("status") != "ok":
        raise RuntimeError(f"Unexpected API payload: {raw!r}"[:500])
    data = raw.get("data") or {}
    entries = data.get("entries") or []
    meta = data.get("meta") or {}
    if not isinstance(entries, list):
        raise RuntimeError("entries is not a list")
    return entries, meta if isinstance(meta, dict) else {}


def render_markdown(entries: list[dict], meta: dict) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        "<!--",
        "  AUTO-GENERATED — do not edit by hand.",
        "  Regenerated by .github/workflows/sync-curated-registry.yml",
        f"  Source: {API_URL}",
        "-->",
        "",
        "# Curated MCP Registry (mirror)",
        "",
        "Editor-reviewed listings from "
        f"[agentshare.dev/registry]({REGISTRY_HTML}).",
        "",
        "**This is a discovery mirror only.** It is **not** the AgentShare product MCP tool list "
        "(see [README](../README.md) § MCP tools). Third-party servers require their own auth; "
        "AgentShare does not proxy or custody them.",
        "",
        f"- **Generated (UTC):** `{now}`  ",
        f"- **Live JSON:** `{API_URL}`  ",
        f"- **Count:** {len(entries)} verified  ",
        "",
    ]
    pin = meta.get("pin_note")
    if pin:
        lines.append(f"> {pin}")
        lines.append("")

    lines.extend(
        [
            "| ID | Name | Category | MCP | Website | GitHub | Hub |",
            "|---:|------|----------|-----|---------|--------|-----|",
        ]
    )

    for e in entries:
        eid = e.get("id", "")
        name = _esc_cell(e.get("name") or f"#{eid}")
        cat = _esc_cell(e.get("category_label") or e.get("category") or "—")
        mcp = e.get("mcp_url")
        web = e.get("website_url")
        gh = e.get("github_url")
        hub = (e.get("urls") or {}).get("html") if isinstance(e.get("urls"), dict) else None
        if not hub and eid != "":
            hub = f"{REGISTRY_HTML}/{eid}"
        pin_mark = " [pin]" if e.get("pinned") else ""
        lines.append(
            "| "
            + " | ".join(
                [
                    str(eid),
                    f"{name}{pin_mark}",
                    cat,
                    _md_link("mcp", mcp) if mcp else "—",
                    _md_link("site", web) if web else "—",
                    _md_link("repo", gh) if gh else "—",
                    _md_link("page", hub) if hub else "—",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## How this stays in sync",
            "",
            "GitHub Action `Sync curated registry` fetches verified entries daily "
            "(and on manual run) and commits this file when the table changes.",
            "",
            "Submit / request review: "
            f"[registry submit]({REGISTRY_HTML}#submit).",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    out = root / OUT_REL
    try:
        entries, meta = fetch_entries()
    except urllib.error.HTTPError as e:
        print(f"HTTP {e.code} fetching registry: {e.reason}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Failed to fetch registry: {e}", file=sys.stderr)
        return 1

    text = render_markdown(entries, meta)
    out.parent.mkdir(parents=True, exist_ok=True)
    prev = out.read_text(encoding="utf-8") if out.is_file() else None
    # Ignore generated timestamp when deciding "changed" for quieter commits:
    # compare body without the Generated line.
    def _stable(s: str) -> str:
        return "\n".join(
            ln for ln in s.splitlines() if not ln.startswith("- **Generated (UTC):**")
        )

    if prev is not None and _stable(prev) == _stable(text):
        print("No content change (excluding timestamp).")
        # Still refresh timestamp lightly? Prefer no commit noise — leave file as-is.
        return 0

    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {out} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
